accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

groups/urls.py
from django.urls import path
from . import views

app_name ='groups'

urlpatterns = [
    path('', views.ListGroups.as_view(),name='all_groups'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/<slug>',views.GroupDetail.as_view(),name='group_detail')
]

posts/urls.py
from django.urls import path
from . import views

app_name ='posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all_posts'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('<username>/',views.UserPosts.as_view(),name='for_user'),
    path('<username>/<pk>',views.PostDetail.as_view(),name='post_detail'),
    path('delete/<pk>',views.DeletePost.as_view(),name='delete')
]

space_social/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomeView.as_view(),name='home'),
    path('login_redirect',views.LogInRedirectPage.as_view(),name='login_redirect'),
    path('logout_redirect',views.LogOutRedirectPage.as_view(),name='logout_redirect'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return f"@{self.username}"

groups/models.py
from django.db import models
from django.utils.text import slugify
import misaka
from django.contrib.auth import get_user_model
from django import template
from django.urls import reverse

# Create your models here.

User = get_user_model()

register = template.Library()

class Group(models.Model):
    name = model.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    memebers = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})    
    
    class Meta:
        ordering=['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships')
    user = models.ForeignKey(User,related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group','user')

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import misaka
from groups.models import Group
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,related_name='user_posts')
    created_at = models.DateTimeField(auto_now=True)
    post = models.TextField()
    post_html = models.TextField(editable=False)
    group = models.ForeignKey(Group,related_name='posts',null=True,blank=True)

    def __str__(self):
        return self.message
    
    def save(self,*args,**kwargs):
        self.post_html = misaka.html(self.post)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})  


    class Meta:
        ordering = ['-created_at'] 
        unique_together = ['user','post']

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserSignupForm(UserCreationForm):

    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Blog Handle'
        self.fields['email'].label = 'Email Address'

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms

# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserSignupForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionsRequiredMixin
from django.core.urlresolvers import reverse
from django.views import generic
from group.models import Group

# Create your views here.

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name','description')
    model = Group


class GroupDetail(generic.DetailView):
    model = Group


class ListGroups(generic.ListView):
    model = Group
 

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.views import Http404
from braces.views import SelectRelatedMixin
from . import models
from . import forms
from django.contrib.auth import get_user_model

# Create your views here.

User = get_user_model()

class PostList(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ('user','group')


class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'post/user_post_list.html'

    def get_queryset(self):
        try:
            self.post.user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoseNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields = ('message','group')
    model = models.Post

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = model.Post
    selet_related = ('user','group')
    success_url = reverse_lazy('posts:all_posts')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

space_social/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'index.html'


class LogInRedirectPage(TemplateView):
    template_name = 'login_redirect.html'


class LogOutRedirectPage(TemplateView):
    template_name = 'logout_redirect.html'

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

<div class="jumbotron">
    <h1>Log In</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class='btn btn-default' value='Login'>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

<div class="jumbotron">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class='btn btn-default' value='Sign Up'>
    </form>
</div>

{% endblock %}

groups/templates/groups/group_base.html
{% extends "base.html %}
{% block content %}

<div class="container">

    <div class="row">
        {% block pregoup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>

</div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html %}
{% block pregoup %}

<h1> {{group.name}} </h1>
<h2> {{group.member.count}} group members</h2>

<div class="content">

    {% if user in group.members.all %}
        <a href="{% url 'groups:leave' slug=group.slug %}" class='btn btn-lg btn-fill btn-warning'>
            <span class='glyphicon glyphicon-remove-circle'></span>Leave
        </a>
    {% else %}
        <a href="{% url 'groups:join' slug=group.slug %}" class='btn btn-lg btn-fill btn-warning'>
            <span class='glyphicon glyphicon-ok-circle'></span>Join
        </a>
    {% endif %}

</div>

{% endblock %}
{% block gorup_content %}

<div class="col-md-8">
    {% if groups.posts.count ==0 %}
    <h2>This group has no posts yet!</h2>
    {% else %}
        {% for post in group.posts.all %}
            {% include "posts/_post.html" %}
        {% endfor %}
    {% endif %}
</div>
    

{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html %}
{% load booststrap3 %}

{% block group_content %}
<h4> Create a new Group</h4>
<form action="{% url 'group:create %}'" method="POST" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="Create">
</form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html %}
{% block pregoup %}

<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>Welcome back
            <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a>
        </h2>
        {% endif%}
        <h2>Gorups</h2>
        <p>Welcome to the groups page!</p>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
        <span class="glyphicon glyphicon-plus-sign">Create New Group</span>
    </a>
    {% endif %}
</div>

{% endblock %}
{% block group_content %}

<div class="col-md-8">
    <div class="list-group">
        {% for grpup in object_list %}
        <a href="{% url 'groups:group_detail' slug=group.slug %}" class="list-group-item">
            <h3 class="title list-group-item-heading">{{group.name}}</h3>
            <div class="list-group-item-text container-fluid">
                {{group.description_html|pluralize}}
                <div class="row">
                    <div class="col-md-4"><span class="badge">{{group.members.count}}</span> member{{group.members.count|pluralize}}</div>
                    <div class="col-md-4"><span class="badge">{{group.posts.count}}</span> post{{group.posts.count|pluralize}}</div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
    
{% endblock %}

posts/templates/posts/_post.html
<div class="post media">
    <h3>{{post.post_html|safe}}</h3>
    <div class="media-body">

    </div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html %}
{% block content %}

<div class="posts-page">
    <div class="container">
        <div class="row">
            {% block prepost %}{% endblock %}
            {% block post_content %}{% endblock %}
            {% block post_post %}{% endblock %}
        </div>
    </div>
</div>

{% endblock %}

posts/templates/posts/post_form.html
{% extends "post/post_base.html %}
{% load booststrap3 %}

{% block post_content %}
<h4> Create a new Post</h4>
<form action="{% url 'posts:create %}'" method="POST" id="postForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="Post">
</form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "groups/group_base.html %}
{% block pregoup %}

<div class="col-md-4">
    {% if user.is_authenticated %}
    <div class="card card-with-shadow">
        <div class="content">
            <h5 class="title">Your Groups</h5>
            <ul class="list-unstyled">
                {% for member_group in get_user_groups %}
                <li class="group li-with-bullet">
                    <a href="{% url 'groups:group_detail' slug=member_group.group.slug %}"></a>
                </li>
                {% enfor %}
            </ul>
        </div>
    </div>
    {% endif%}

    <div class="card card-with-shadow">
        <div class="content">
            <h5 class="title">All Groups</h5>
            <ul class="list-unstyled">
                {% for other_group in get_other_groups %}
                <li class="group li-with-bullet">
                    <a href="{% url 'groups:group_detail' slug=other_group.group.slug %}"></a>
                </li>
                {% enfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}
{% block post_content %}

<div class="col-md-8">
    {% for post in post_list %}
        {% include "posts/_post.html" %}
    {% endfor %}
</div>
    
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Space Social</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"><script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet"> 

    <link rel="stylesheet" href="{% static 'space_blog/css/master.css' %}">
</head>
<body>

    <nav class="navbar mynav" role="navigation" id="navbar">
        <div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Space Social</a>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="">Post</a></li>
                    <li><a href="">Groups</a></li>
                    <li><a href="">Create Group</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                    <li><a href="">Groups</a></li>
                    <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>                    
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container basebodydiv">
    {% block content %}

    {% endblock %}
    </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Space Social</h1>

{% endblock %}

templates/login_redirect.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_authenticated %}
    <h1>Welcome {{user.username}} </h1>
    {% endif %}

{% endblock %}

templates/logout_redirect.html
{% extends "base.html" %}

{% block content %}

<h1>Come back soon, cheers!!</h1>

{% endblock %} 